export const lightTheme = {
  primary: '#5C6BC0',
  accent: '#A1887F',
  secondaryAccent: '#4DB6AC',
  background: '#FAFAFA',
  surface: '#F5F5F0',
  border: '#E0E0E0',
  text: '#212121',
  textDim: '#757575',
  error: '#E57373',
  typography: {
    headline: { fontFamily: 'Poppins', fontSize: 24, fontWeight: '600' },
    subheadline: { fontFamily: 'Inter', fontSize: 18, fontWeight: '500' },
    body: { fontFamily: 'Inter', fontSize: 16, fontWeight: '400' },
    caption: { fontFamily: 'Inter', fontSize: 12, fontWeight: '500' },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  radius: {
    sm: 4,
    md: 8,
    lg: 16,
  },
  shadow: {
    light: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 3,
      elevation: 2,
    },
    medium: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 6,
      elevation: 4,
    },
  },
};

export const darkTheme = {
  primary: '#9FA8DA',
  accent: '#D7CCC8',
  secondaryAccent: '#80CBC4',
  background: '#121212',
  surface: '#1E1E1E',
  border: '#333333',
  text: '#F5F5F5',
  textDim: '#BDBDBD',
  error: '#EF9A9A',
  typography: {
    headline: { fontFamily: 'Poppins', fontSize: 24, fontWeight: '600' },
    subheadline: { fontFamily: 'Inter', fontSize: 18, fontWeight: '500' },
    body: { fontFamily: 'Inter', fontSize: 16, fontWeight: '400' },
    caption: { fontFamily: 'Inter', fontSize: 12, fontWeight: '500' },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  radius: {
    sm: 4,
    md: 8,
    lg: 16,
  },
  shadow: {
    light: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.3,
      shadowRadius: 3,
      elevation: 2,
    },
    medium: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.4,
      shadowRadius: 6,
      elevation: 4,
    },
  },
};
